<a href="https://colab.research.google.com/github/KodumuruRaja/Feature-Selection/blob/main/Feature-Selection-(Dropping%20Constant-Features).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data=pd.DataFrame({'A':[1,2,3,1,2,3],
                   'B':[4,5,6,7,8,9],
                   'C':[0,0,0,0,0,0],
                   'D':[1,1,1,1,1,1]})

In [ ]:
data.head()

   A  B  C  D
0  1  4  0  1
1  2  5  0  1
2  3  6  0  1
3  1  7  0  1
4  2  8  0  1

# **Drop Constant Features**

In [ ]:
# It will drop Zero Variance Features
from sklearn.feature_selection import VarianceThreshold
var=VarianceThreshold(threshold=0)
var.fit(data)

VarianceThreshold(threshold=0)

In [ ]:
var.get_support()

array([ True,  True, False, False])

In [ ]:
data.columns[var.get_support()]

Index(['A', 'B'], dtype='object')

In [ ]:
constant_columns=[column for column in data.columns
                  if column not in data.columns[var.get_support()]]

In [ ]:
len(constant_columns)

2

In [ ]:
for feature in constant_columns:
  print(feature)

C
D

In [ ]:
data.drop(constant_columns,axis=1)

   A  B
0  1  4
1  2  5
2  3  6
3  1  7
4  2  8
5  3  9

In [ ]:
# Dropping Constant Features in DataSEt
import pandas as pd
from sklearn.feature_selection import VarianceThreshold

In [ ]:
data=pd.read_csv("/content/train.csv")

In [ ]:
data.shape

(10744, 371)

In [ ]:
data.head()

   ID  var3  var15  ...  saldo_medio_var44_ult3          var38  TARGET
0   1     2     23  ...                     0.0   39205.170000     0.0
1   3     2     34  ...                     0.0   49278.030000     0.0
2   4     2     23  ...                     0.0   67333.770000     0.0
3   8     2     37  ...                     0.0   64007.970000     0.0
4  10     2     39  ...                     0.0  117310.979016     0.0

[5 rows x 371 columns]

In [ ]:
x=data.drop(labels=['TARGET'],axis=1)
y=data['TARGET']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

In [ ]:
x_train.shape,x_test.shape

((7520, 370), (3224, 370))

In [ ]:
# Applying Variance Threshold
var=VarianceThreshold(threshold=0)
var.fit(x_train)

VarianceThreshold(threshold=0)

In [ ]:
sum(var.get_support())

285

In [ ]:
len(x_train.columns[var.get_support()])

285

In [ ]:
cc=[column for column in x_train.columns if column not in x_train.columns[var.get_support()]]

In [ ]:
len(cc)

85

In [ ]:
for column in cc:
  print(column)

ind_var2_0
ind_var2
ind_var13_medio_0
ind_var13_medio
ind_var18_0
ind_var18
ind_var27_0
ind_var28_0
ind_var28
ind_var27
ind_var34_0
ind_var34
ind_var41
ind_var46_0
ind_var46
num_var13_medio_0
num_var13_medio
num_var18_0
num_var18
num_var27_0
num_var28_0
num_var28
num_var27
num_var34_0
num_var34
num_var41
num_var46_0
num_var46
saldo_var13_medio
saldo_var18
saldo_var28
saldo_var27
saldo_var34
saldo_var41
saldo_var46
delta_imp_amort_var18_1y3
delta_imp_amort_var34_1y3
delta_imp_reemb_var17_1y3
delta_imp_reemb_var33_1y3
delta_imp_trasp_var17_out_1y3
delta_imp_trasp_var33_out_1y3
delta_num_reemb_var17_1y3
delta_num_reemb_var33_1y3
delta_num_trasp_var17_out_1y3
delta_num_trasp_var33_out_1y3
imp_amort_var18_hace3
imp_amort_var18_ult1
imp_amort_var34_hace3
imp_amort_var34_ult1
imp_var7_emit_ult1
imp_reemb_var13_hace3
imp_reemb_var17_hace3
imp_reemb_var17_ult1
imp_reemb_var33_hace3
imp_reemb_var33_ult1
imp_trasp_var17_in_hace3
imp_trasp_var17_out_hace3
imp_trasp_var17_out_ult1
imp_trasp_var33_in_hace3
imp_trasp_var33_out_hace3
imp_trasp_var33_out_ult1
imp_venta_var44_hace3
ind_var7_emit_ult1
num_var2_0_ult1
num_var2_ult1
num_var7_emit_ult1
num_meses_var13_medio_ult3
num_reemb_var13_hace3
num_reemb_var17_hace3
num_reemb_var17_ult1
num_reemb_var33_hace3
num_reemb_var33_ult1
num_trasp_var17_in_hace3
num_trasp_var17_out_hace3
num_trasp_var17_out_ult1
num_trasp_var33_in_hace3
num_trasp_var33_out_hace3
num_trasp_var33_out_ult1
num_venta_var44_hace3
saldo_var2_ult1
saldo_medio_var13_medio_hace2
saldo_medio_var13_medio_hace3
saldo_medio_var13_medio_ult1
saldo_medio_var13_medio_ult3
saldo_medio_var29_hace3

In [ ]:
x_train.drop(cc,axis=1)

         ID  var3  ...  saldo_medio_var44_ult3          var38
3034   6103     2  ...                     0.0  159715.380000
8105  16354     2  ...                     0.0   79804.830000
3050   6125     2  ...                     0.0  117310.979016
2229   4475     2  ...                     0.0   64656.360000
2916   5833     2  ...                     0.0   89526.810000
...     ...   ...  ...                     ...            ...
9225  18564     2  ...                     0.0  117547.890000
4859   9723     2  ...                     0.0   71050.830000
3264   6557     2  ...                     0.0  141069.330000
9845  19796     2  ...                     0.0   86412.150000
2732   5441     2  ...                     0.0   45985.680000

[7520 rows x 285 columns]